frontend:
  build: frontend/
  volumes:
      - "./frontend:/frontend"
      - "./frontend/src:/src"
      - "./frontend/assets:/assets"
      - "./frontend/dist:/dist"
      - "./frontend/package.json:/package.json"
    ports:
        - "8080:8080"